### ISSUE TITLE
Issue to run "imp.disch.T_plot()"

### ISSUE THREAD

**Issue by Hempstead** [petrobras/ccp#46]
Hi, All,

I have issues to run the following code:

import os
os.environ['RPPREFIX'] = "C:\Program Files (x86)\REFPROP"
import ccp
import ccp
import tqdm as notebook_tqdm

ccp.config.EOS = "HEOS"  # no need to modify the init file directly, you can set the eos here.

# ccp uses pint to handle units. Q_ is a pint quantity.
# If a pint quantity is not provided, SI units are assumed.
Q_ = ccp.Q_
ps = Q_(3, 'bar')
Ts = 300

# Define the fluid as a dictionary:
fluid = {
    "CarbonDioxide": 0.8,
    "Nitrogen": 0.2,
}

# Define suction and discharge states:

suc0 = ccp.State(fluid=fluid, p=ps, T=Ts)
disch0 = ccp.State(fluid=fluid, p=Q_(7.255, 'bar'), T=391.1)
disch1 = ccp.State(fluid=fluid, p=Q_(6.754, 'bar'), T=382.1)

# Create performance point(s):

point0 = ccp.Point(
    suc=suc0,
    disch=disch0,
    speed=Q_(7941, 'RPM'),
    flow_m=Q_(34203.6, 'kg/hr'),
    b=0.0285,
    D=0.365,
)
point1 = ccp.Point(
    suc=suc0,
    disch=disch1,
    speed=Q_(7941, 'RPM'),
    flow_m=Q_(36204.8, 'kg/hr'),
    b=0.0285,
    D=0.365,
)

# Create an impeller with those points:

imp = ccp.Impeller([point0, point1])

# Get results from the Impeller with methods such as
imp.head_plot()
imp.disch.T_plot()

specially got error with "imp.disch.T_plot()"

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], line 52
     50 # Get results from the Impeller with methods such as
     51 imp.head_plot()
---> 52 imp.disch.T_plot()

File ~\.conda\envs\comp\lib\site-packages\ccp\config\units.py:187, in check_units.<locals>.inner(*args, **kwargs)
    184     else:
    185         base_unit_kwargs[k] = v
--> 187 return func(*base_unit_args, **base_unit_kwargs)

File ~\.conda\envs\comp\lib\site-packages\ccp\impeller.py:121, in ImpellerPlotFunction.__call__(self, flow_v, speed, plot_kws, *args, **kwargs)
    118 surge_flow_list = []
    119 surge_attr_list = []
    120 attr_units = kwargs.get(
--> 121     f"{attr}_units", getattr(impeller_object.curves[0], attr).units
    122 )
    124 for curve in impeller_object.curves:
    125     fig = r_getattr(curve, attr + "_plot")(fig=fig, plot_kws=plot_kws, **kwargs)

AttributeError: 'Curve' object has no attribute 'disch.T'

**Comment by raphaeltimbo** [comment]
Hi @Hempstead! 
Yes, this is a bug. I will try to solve it as soon as possible and will make a new release.

**Comment by Hempstead** [comment]
Thanks a lot!

**Comment by raphaeltimbo** [comment]
Hi @Hempstead!
I have just released v0.3.6 with the fix.
You can install with pip install -U ccp-performance.
Let me know if you still have issues.

**Comment by Hempstead** [comment]
It works now! Thank you so much!

**Comment by Hempstead** [comment]
I have to add "import tqdm as notebook_tqdm" in order to run ccp
